//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Licenses
    {
        public tbl_Licenses()
        {
            this.tbl_Person_Licenses = new HashSet<tbl_Person_Licenses>();
        }
    
        public int LicenseID { get; set; }
        public string LicenseDesc { get; set; }
        public int LicenseTypeID { get; set; }
        public int LicenseIssuerID { get; set; }
        public int LicenseLevelID { get; set; }
    
        public virtual tbl_License_Levels tbl_License_Levels { get; set; }
        public virtual ICollection<tbl_Person_Licenses> tbl_Person_Licenses { get; set; }
    }
}
