//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Conference_Sponsors
    {
        public int ConferenceSponsorID { get; set; }
        public int ConferenceID { get; set; }
        public int OrganizationID { get; set; }
        public int FeeMasterID { get; set; }
        public bool PrimarySponsor { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual tbl_Conferences tbl_Conferences { get; set; }
        public virtual tbl_Fee_Master tbl_Fee_Master { get; set; }
        public virtual tbl_Organizations tbl_Organizations { get; set; }
    }
}
