//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_District_Sites
    {
        public int DistrictSiteID { get; set; }
        public int DistrictID { get; set; }
        public int SiteID { get; set; }
    
        public virtual tbl_Districts tbl_Districts { get; set; }
        public virtual tbl_Sites tbl_Sites { get; set; }
    }
}
