//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Venue_Types
    {
        public tbl_Venue_Types()
        {
            this.tbl_Conference_Venue_Types = new HashSet<tbl_Conference_Venue_Types>();
            this.tbl_Course_Venue_Options = new HashSet<tbl_Course_Venue_Options>();
        }
    
        public int VenueTypeID { get; set; }
        public string VenueTypeDesc { get; set; }
    
        public virtual ICollection<tbl_Conference_Venue_Types> tbl_Conference_Venue_Types { get; set; }
        public virtual ICollection<tbl_Course_Venue_Options> tbl_Course_Venue_Options { get; set; }
    }
}
