//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Organization_Professions
    {
        public int Organization_Profession_ID { get; set; }
        public Nullable<int> Organization_ID { get; set; }
        public Nullable<int> Profession_ID { get; set; }
    }
}
