//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Presenters
    {
        public tbl_Presenters()
        {
            this.tbl_Course_Presenters = new HashSet<tbl_Course_Presenters>();
        }
    
        public int PresenterID { get; set; }
        public int PersonID { get; set; }
    
        public virtual ICollection<tbl_Course_Presenters> tbl_Course_Presenters { get; set; }
    }
}
