//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PersonOrganizationMemberships
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<System.DateTime> DateMembershipExpires { get; set; }
        public Nullable<System.DateTime> JoinOnDate { get; set; }
        public Nullable<decimal> Dues { get; set; }
        public Nullable<System.DateTime> PaidOnDate { get; set; }
        public string MembershipID { get; set; }
    }
}
