//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Fee_Master
    {
        public tbl_Fee_Master()
        {
            this.tbl_Conference_Sponsors = new HashSet<tbl_Conference_Sponsors>();
            this.tbl_Course_Sponsors = new HashSet<tbl_Course_Sponsors>();
            this.tbl_Fee_Details = new HashSet<tbl_Fee_Details>();
        }
    
        public int FeeMasterID { get; set; }
        public string DummyColumn { get; set; }
    
        public virtual ICollection<tbl_Conference_Sponsors> tbl_Conference_Sponsors { get; set; }
        public virtual ICollection<tbl_Course_Sponsors> tbl_Course_Sponsors { get; set; }
        public virtual ICollection<tbl_Fee_Details> tbl_Fee_Details { get; set; }
    }
}
