//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Issuers
    {
        public tbl_Issuers()
        {
            this.tbl_Course_Credit_Issuers = new HashSet<tbl_Course_Credit_Issuers>();
        }
    
        public int IssuerID { get; set; }
        public int OrganizationID { get; set; }
        public string CEUIssuerNbr { get; set; }
        public int AuthorizedPersonID { get; set; }
        public string AuthorizedSignaturePath { get; set; }
    
        public virtual ICollection<tbl_Course_Credit_Issuers> tbl_Course_Credit_Issuers { get; set; }
        public virtual tbl_Organizations tbl_Organizations { get; set; }
    }
}
