//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Fee_Types
    {
        public tbl_Fee_Types()
        {
            this.tbl_Fee_Details = new HashSet<tbl_Fee_Details>();
        }
    
        public int FeeTypeID { get; set; }
        public string FeeTypeDesc { get; set; }
    
        public virtual ICollection<tbl_Fee_Details> tbl_Fee_Details { get; set; }
    }
}
