//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course_Enrollment
    {
        public int CourseEnrollmentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> EnrollmentMasterID { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<int> FeeMasterID { get; set; }
        public int FeePaymentStatus { get; set; }
        public Nullable<int> FeePaidOrganizationID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<bool> VideoViewed { get; set; }
    
        public virtual tbl_Courses tbl_Courses { get; set; }
        public virtual tbl_Enrollment_Master tbl_Enrollment_Master { get; set; }
    }
}
