//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Providers
    {
        public int ProviderID { get; set; }
        public int OrganizationID { get; set; }
    
        public virtual tbl_Organizations tbl_Organizations { get; set; }
    }
}
