//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Districts
    {
        public tbl_Districts()
        {
            this.tbl_District_Sites = new HashSet<tbl_District_Sites>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
    
        public virtual ICollection<tbl_District_Sites> tbl_District_Sites { get; set; }
    }
}
