//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Conference_Dates
    {
        public int ConferenceDateID { get; set; }
        public int ConferenceID { get; set; }
        public System.DateTime ConferenceDate { get; set; }
    }
}
