//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ecommerce_Transactions
    {
        public int EcommerceTransactionID { get; set; }
        public Nullable<int> EnrollmentMasterID { get; set; }
        public string PaymentProcessorTransactionCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> OrganizationID { get; set; }
    }
}
