//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Person_Degrees
    {
        public int PersonDegreeID { get; set; }
        public int PersonID { get; set; }
        public int DegreeID { get; set; }
    
        public virtual tbl_Degrees tbl_Degrees { get; set; }
        public virtual tbl_Person tbl_Person { get; set; }
    }
}
