//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Attendance
    {
        public tbl_Attendance()
        {
            this.tbl_Course_Survey = new HashSet<tbl_Course_Survey>();
        }
    
        public int AttendanceID { get; set; }
        public int EnrollmentMasterID { get; set; }
    
        public virtual tbl_Enrollment_Master tbl_Enrollment_Master { get; set; }
        public virtual ICollection<tbl_Course_Survey> tbl_Course_Survey { get; set; }
    }
}
