//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OnlineCourses
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public string FileName { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> AvailabilityStartDate { get; set; }
        public Nullable<System.DateTime> AvailabilityEndDate { get; set; }
    }
}
