//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Persons_Professions
    {
        public int Person_Profession_ID { get; set; }
        public int Person_ID { get; set; }
        public Nullable<int> Profession_ID { get; set; }
    
        public virtual tbl_Person tbl_Person { get; set; }
        public virtual tbl_professions tbl_professions { get; set; }
    }
}
