//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Current_User
    {
        public int CurrentUserID { get; set; }
        public int PersonOrganizationRoleID { get; set; }
        public System.Guid SessionGuid { get; set; }
        public System.DateTime LoggedInDatm { get; set; }
    }
}
