//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course_Survey
    {
        public tbl_Course_Survey()
        {
            this.tbl_Survey_Results = new HashSet<tbl_Survey_Results>();
        }
    
        public int CourseSurveyID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> AttendanceID { get; set; }
        public int CourseIssuerID { get; set; }
        public Nullable<int> EnrollmentMasterID { get; set; }
    
        public virtual tbl_Attendance tbl_Attendance { get; set; }
        public virtual tbl_Survey tbl_Survey { get; set; }
        public virtual ICollection<tbl_Survey_Results> tbl_Survey_Results { get; set; }
    }
}
