//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConferenceEnrollment
    {
        public int ConferenceEnrollmentID { get; set; }
        public int ConferenceID { get; set; }
        public int PersonID { get; set; }
        public int EnrollmentMasterID { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public Nullable<int> FeeMasterID { get; set; }
        public Nullable<int> FeePaymentStatus { get; set; }
        public Nullable<int> FeePaidOrganizationID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
    
        public virtual tbl_Conferences tbl_Conferences { get; set; }
        public virtual tbl_Enrollment_Master tbl_Enrollment_Master { get; set; }
        public virtual tbl_Person tbl_Person { get; set; }
    }
}
