//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_License_Levels
    {
        public tbl_License_Levels()
        {
            this.tbl_Licenses = new HashSet<tbl_Licenses>();
        }
    
        public int LicenseLevelID { get; set; }
        public string LicenseLevel { get; set; }
    
        public virtual ICollection<tbl_Licenses> tbl_Licenses { get; set; }
    }
}
