//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Event_Facilities
    {
        public tbl_Event_Facilities()
        {
            this.tbl_Conference_Facilities = new HashSet<tbl_Conference_Facilities>();
            this.tbl_Course_Facilities = new HashSet<tbl_Course_Facilities>();
        }
    
        public int EventFacilityID { get; set; }
        public int FacilityID { get; set; }
    
        public virtual ICollection<tbl_Conference_Facilities> tbl_Conference_Facilities { get; set; }
        public virtual ICollection<tbl_Course_Facilities> tbl_Course_Facilities { get; set; }
        public virtual tbl_Facilities tbl_Facilities { get; set; }
    }
}
