//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Degree_Types
    {
        public tbl_Degree_Types()
        {
            this.tbl_Degrees = new HashSet<tbl_Degrees>();
        }
    
        public int DegreeTypeID { get; set; }
        public string DegreeTypeDesc { get; set; }
    
        public virtual ICollection<tbl_Degrees> tbl_Degrees { get; set; }
    }
}
