//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Survey_Questions
    {
        public tbl_Survey_Questions()
        {
            this.tbl_Survey_Results = new HashSet<tbl_Survey_Results>();
        }
    
        public int SurveyQuestionID { get; set; }
        public int SurveyID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> QuestionOrder { get; set; }
    
        public virtual tbl_Questions tbl_Questions { get; set; }
        public virtual tbl_Survey tbl_Survey { get; set; }
        public virtual ICollection<tbl_Survey_Results> tbl_Survey_Results { get; set; }
    }
}
