//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Facilities
    {
        public tbl_Facilities()
        {
            this.tbl_Event_Facilities = new HashSet<tbl_Event_Facilities>();
        }
    
        public int FacilityID { get; set; }
        public string FacilityDesc { get; set; }
        public int VenueTypeID { get; set; }
        public string Address { get; set; }
        public int CityID { get; set; }
    
        public virtual ICollection<tbl_Event_Facilities> tbl_Event_Facilities { get; set; }
    }
}
