//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Role_Types
    {
        public tbl_Role_Types()
        {
            this.tbl_Roles = new HashSet<tbl_Roles>();
        }
    
        public int RoleTypeID { get; set; }
        public string RoleTypeDesc { get; set; }
    
        public virtual ICollection<tbl_Roles> tbl_Roles { get; set; }
    }
}
