//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CEU_Certificate_Download
    {
        public long ID { get; set; }
        public int PersonID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime OrignalDownloadDate { get; set; }
        public string ActivityNbr { get; set; }
        public int NoOfDownloads { get; set; }
        public System.DateTime DuplicateDownloadDate { get; set; }
    
        public virtual tbl_Person tbl_Person { get; set; }
        public virtual tbl_Courses tbl_Courses { get; set; }
    }
}
