//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Degrees
    {
        public tbl_Degrees()
        {
            this.tbl_Person_Degrees = new HashSet<tbl_Person_Degrees>();
        }
    
        public int DegreeID { get; set; }
        public string DegreeDesc { get; set; }
        public int DegreeTypeID { get; set; }
    
        public virtual tbl_Degree_Types tbl_Degree_Types { get; set; }
        public virtual ICollection<tbl_Person_Degrees> tbl_Person_Degrees { get; set; }
    }
}
