//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Licensing
    {
        public int LincenseID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Organization_ID { get; set; }
        public Nullable<System.DateTime> LicenseExpirationDate { get; set; }
        public Nullable<decimal> Fee_Origination { get; set; }
        public Nullable<decimal> Fee_Annual { get; set; }
        public Nullable<decimal> Fee_Transactional { get; set; }
        public Nullable<int> Account_Rep { get; set; }
        public Nullable<System.DateTime> LicenseOriginationDate { get; set; }
    
        public virtual tbl_Licensing tbl_Licensing1 { get; set; }
        public virtual tbl_Licensing tbl_Licensing2 { get; set; }
        public virtual tbl_Person tbl_Person { get; set; }
    }
}
