//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Person_Organization_Roles
    {
        public int PersonOrganizationRoleID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public int OrganizationID { get; set; }
        public int RoleID { get; set; }
        public int RoleTypeID { get; set; }
        public string Pwd { get; set; }
        public Nullable<bool> AdminApproval { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
    
        public virtual tbl_Organizations tbl_Organizations { get; set; }
        public virtual tbl_Person tbl_Person { get; set; }
        public virtual tbl_Roles tbl_Roles { get; set; }
    }
}
