//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Conference_Venue_Types
    {
        public int ConferenceVenueTypeID { get; set; }
        public int ConferenceID { get; set; }
        public int VenueTypeID { get; set; }
    
        public virtual tbl_Conferences tbl_Conferences { get; set; }
        public virtual tbl_Venue_Types tbl_Venue_Types { get; set; }
    }
}
