//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceu_Education_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Credential_Phrases
    {
        public long CredentialPhraseID { get; set; }
        public string CredentialPhrase { get; set; }
        public bool HasBeenIssued { get; set; }
        public Nullable<int> EnrollmentMasterID { get; set; }
    }
}
